# Railway deployment configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "gunicorn app:app"
  healthcheckPath = "/"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
